### ISSUE TITLE
Impossible run  ansible-playbook without error on mac

### ISSUE THREAD

**Issue by okamara** [qaprosoft/mcloud#35]
Execute:
 ansible-playbook -vvv -i hosts devices.yml --tags "registerDevice"

Error message appears:
fatal: [localhost]: FAILED! => {
    "ansible_facts": {}, 
    "changed": false, 
    "failed_modules": {
        "setup": {
            "ansible_facts": {
                "discovered_interpreter_python": "/usr/bin/python"
            }, 
            "deprecations": [
                {
                    "msg": "Distribution Ubuntu 16.04 on host localhost should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information", 
                    "version": "2.12"
                }
            ], 
            "failed": true, 
            "module_stderr": "sudo: a password is required\n", 
            "module_stdout": "", 
            "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
            "rc": 1
        }
    }, 
    "msg": "The following modules failed to execute: setup\n"
}

**Comment by vdelendik** [comment]
won't fix
