### ISSUE TITLE
Model and Product of devices should be from main.yml in stf

### ISSUE THREAD

**Issue by okamara** [qaprosoft/mcloud#37]
Open http://stage.solvd.com/
Verify device Model and Product 
Actual result: Model and Product  are from device
Expected: Model and Product of devices should be from main.yml in stf

<img width="1083" alt="Screen Shot 2020-03-11 at 2 20 30 PM" src="https://user-images.githubusercontent.com/32964663/76411926-d1dd9400-63a3-11ea-891c-e1ed9403bcdb.png">

**Comment by dhreben** [comment]
Android works good

**Comment by vdelendik** [comment]
fixed for iOS devices as well
