### ISSUE TITLE
Unable to interact with some devices via STF

### ISSUE THREAD

**Issue by rkatuzhanets** [qaprosoft/mcloud#39]
**OS:** android 7.0-9 

**Description:**
While working with different devices sometimes we couldn't use them manually in STF due to grey screen issue. Meanwhile, all automation tests could be executed properly on the same devices.

P.S. From personal observations, this issue is actual, when device's docker container wasn't restarted for a long period of time (2+ weeks)
<img width="419" alt="greyScreen" src="https://user-images.githubusercontent.com/21850997/78186593-a6ffd080-7475-11ea-8d5b-3b6f8242ca14.png">

**Comment by vdelendik** [comment]
9-10 android are supported started from 3.0 release
